# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 04:18
from __future__ import unicode_literals

import OMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=40, verbose_name='Name')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=30, verbose_name='Company Name')),
                ('phone', models.CharField(default=' ', max_length=10, verbose_name='Phone Number')),
                ('repname', models.CharField(default=' ', max_length=30, verbose_name='Representative ')),
                ('repphone', models.CharField(default=' ', max_length=10, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='OwnedDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasedate', models.DateTimeField(auto_now_add=True, verbose_name='Purchased on')),
                ('deliverdate', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=OMS.models.Device, to='OMS.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=' ', max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(default=' ', max_length=30, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('', '')], default='', max_length=1, verbose_name='Gender')),
                ('phone', models.CharField(default=' ', max_length=10, verbose_name='Phone Number')),
                ('email', models.EmailField(default=' ', max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.AddField(
            model_name='owneddevice',
            name='patient',
            field=models.ForeignKey(on_delete=OMS.models.Patient, to='OMS.Patient'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(on_delete=OMS.models.Manufacturer, to='OMS.Manufacturer'),
        ),
    ]
