# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:15
from __future__ import unicode_literals

import OMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Test Date')),
                ('L250', models.SmallIntegerField(default='0', verbose_name='Left: 250')),
                ('L500', models.SmallIntegerField(default='0', verbose_name='Left: 500')),
                ('L1000', models.SmallIntegerField(default='0', verbose_name='Left: 1000')),
                ('L1500', models.SmallIntegerField(default='0', verbose_name='Left: 1500')),
                ('L2000', models.SmallIntegerField(default='0', verbose_name='Left: 2000')),
                ('L3000', models.SmallIntegerField(default='0', verbose_name='Left: 3000')),
                ('L4000', models.SmallIntegerField(default='0', verbose_name='Left: 4000')),
                ('L6000', models.SmallIntegerField(default='0', verbose_name='Left: 6000')),
                ('L8000', models.SmallIntegerField(default='0', verbose_name='Left: 8000')),
                ('R250', models.SmallIntegerField(default='0', verbose_name='Right: 250')),
                ('R500', models.SmallIntegerField(default='0', verbose_name='Right: 500')),
                ('R1000', models.SmallIntegerField(default='0', verbose_name='Right: 1000')),
                ('R1500', models.SmallIntegerField(default='0', verbose_name='Right: 1500')),
                ('R2000', models.SmallIntegerField(default='0', verbose_name='Right: 2000')),
                ('R3000', models.SmallIntegerField(default='0', verbose_name='Right: 3000')),
                ('R4000', models.SmallIntegerField(default='0', verbose_name='Right: 4000')),
                ('R6000', models.SmallIntegerField(default='0', verbose_name='Right: 6000')),
                ('R8000', models.SmallIntegerField(default='0', verbose_name='Right: 8000')),
                ('patient', models.ForeignKey(on_delete=OMS.models.Patient, to='OMS.Patient')),
            ],
        ),
    ]
