# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0004_auto_20170217_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
    ]
