# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0005_auto_20170223_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Became a patient on'),
        ),
    ]
