# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0006_auto_20170224_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.TextField(blank=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.TextField(blank=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='zipcode',
            field=models.IntegerField(blank=True, default=0, max_length=5, verbose_name='Zip Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Phone Number'),
        ),
    ]
