# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0007_auto_20170226_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='repname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Representative '),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='repphone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fname',
            field=models.CharField(blank=True, max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zipcode',
            field=models.IntegerField(blank=True, default=0, verbose_name='Zip Code'),
        ),
    ]
