# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OMS', '0008_auto_20170227_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zipcode',
            field=models.IntegerField(blank=True, verbose_name='Zip Code'),
        ),
    ]
