# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0010_remove_patient_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
    ]
